server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: C##READING_WEB
    password: Hung@123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  jwt:
    expiration: 3600000
    secret: hung414463774
